# Application Metadata
spring.application.name=product-manager-mcp

# MCP Server Identity
spring.ai.mcp.server.title=Product Warehouse
spring.ai.mcp.server.version=1.0.0

spring.main.banner-mode=off
server.port=8080

logging.level.com.mcp.mcpserver=DEBUG
logging.level.org.springframework.ai.mcp=INFO
